#include "baseline_jit_codegen_helper.h"

// The implementation of this function is generated by Deegen
// Note that this function prototype is also hardcoded!
//
extern "C" void deegen_baseline_jit_do_codegen_impl(DeegenBaselineJitCodegenControlStruct*);

