#pragma once

#include "dfg_node.h"

namespace dfg {

// Clean up the initial CFG generated by the frontend:
// 1. Remove unreachable basic blocks
// 2. Remove no-op basic blocks (we disallow empty BB, so frontend workarounds this by emitting BB with only a NOP)
// 3. Remove trivial control flow edges by merging BBs
// 4. Set up predecessor info
//
void RunCleanupControlFlowGraphPass(Graph* graph);

}   // namespace dfg
