print(type(nil))
print(type(false))
print(type(true))
print(type(1))
print(type(0))
print(type(1.2))
print(type(1e100))
print(type(1/0.0))
print(type(0/0.0))
print(type(-1/0.0))
print(type(-0))
print(type("123"))
print(type("xyz"))
print(type({}))
print(type({x=1}))
print(type({[1]=1,[2]=2}))
print(type(function() end))
print(type(coroutine.create(function()end)))

