print(math.sqrt(4))
print(math.sqrt(0))
print(math.sqrt(-1))
print(math.sqrt(0/0.0))
print(math.sqrt(1/0.0))
print(math.sqrt(-1/0.0))
print(math.sqrt(-0.0))
print(math.sqrt(2))
print(math.sqrt(-2))
print(math.sqrt("123"))
print(math.sqrt("123.4"))
print(math.sqrt("1e5"))
print(math.sqrt(9, 12345))
print((pcall(function() print(math.sqrt()) end)))
print((pcall(function() print(math.sqrt("s")) end)))
print((pcall(function() print(math.sqrt(function() end)) end)))
print((pcall(function() print(math.sqrt(nil)) end)))

