function test(v)
	print('value = ', v)
	print("abs(v) = ", math.abs(v))
	print("acos(v) = ", math.acos(v))
	print("asin(v) = ", math.asin(v))
	print("atan(v) = ", math.atan(v))
	print("ceil(v) = ", math.ceil(v))
	print("cos(v) = ", math.cos(v))
	print("cosh(v) = ", math.cosh(v))
	print("deg(v) = ", math.deg(v))
	print("exp(v) = ", math.exp(v))
	print("floor(v) = ", math.floor(v))
	print("frexp(v) = ", math.frexp(v))
	print("log(v) = ", math.log(v))
	print("log10(v) = ", math.log10(v))
	print("modf(v) = ", math.modf(v))
	print("rad(v) = ", math.rad(v))
	print("sin(v) = ", math.sin(v))
	print("sinh(v) = ", math.sinh(v))
	print("sqrt(v) = ", math.sqrt(v))
	print("tan(v) = ", math.tan(v))
	print("tanh(v) = ", math.tanh(v))
end

test(0)
test(-0.0)
test(1)
test(-1)
test(1.23)
test(-1.23)
test(math.pi)
test(-math.pi)
test(1/0.0)
test(-1/0.0)
test(0/0.0)
test(1000.2)
test(-1000.2)
test("-123.4")
test("   123.4   ")
test("  0xFF  ")

