print(os.date())
print(os.date("%d/%m/%Y %H:%M:%S"))
print(os.date("!%Y-%m-%d %H:%M:%S"))
local tbl = os.date("*t")
print(tbl.year)
print(tbl.month)
print(tbl.day)
print(tbl.hour)
print(tbl.min)
print(tbl.sec)
print(tbl.wday)
print(tbl.yday)
print(tbl.isdst)

