print(string.reverse(""))
print(string.reverse("a"))
print(string.reverse("ab"))
print(string.reverse("abc"))
print(string.reverse("abcd"))
print(string.reverse("abcde"))
print(string.reverse("abcdef"))
print(string.reverse("abcdefg"))
print(string.reverse("abcdefgh"))
print(string.reverse("abcdefghi"))
print(string.reverse("abcdefghij"))
print(string.reverse("abcdefghijk"))
print(string.reverse("abcdefghijkl"))
print(string.reverse("abcdefghijklm"))
print(string.reverse("abcdefghijklmn"))
print(string.reverse("abcdefghijklmno"))
print(string.reverse("abcdefghijklmnop"))
print(string.reverse("abcdefghijklmnopq"))
print(string.reverse("abcdefghijklmnopqr"))
print(string.reverse("abcdefghijklmnopqrs"))
print(string.reverse("abcdefghijklmnopqrst"))
print(string.reverse("abcdefghijklmnopqrstu"))
print(string.reverse("abcdefghijklmnopqrstuv"))
print(string.reverse("abcdefghijklmnopqrstuvw"))
print(string.reverse("abcdefghijklmnopqrstuvwx"))
print(string.reverse("abcdefghijklmnopqrstuvwxy"))
print(string.reverse("abcdefghijklmnopqrstuvwxyz"))
print(string.reverse("abcdefghijklmnopqrstuvwxyzA"))
print(string.reverse("abcdefghijklmnopqrstuvwxyzAB"))
print(string.reverse("abcdefghijklmnopqrstuvwxyzABC"))
print(string.reverse("abcdefghijklmnopqrstuvwxyzABCD"))
print(string.reverse("abcdefghijklmnopqrstuvwxyzABCDE"))
print(string.reverse("abcdefghijklmnopqrstuvwxyzABCDEF"))
print(string.reverse("abcdefghijklmnopqrstuvwxyzABCDEFG"))
print(string.reverse("abcdefghijklmnopqrstuvwxyzABCDEFGH"))
print(string.reverse("abcdefghijklmnopqrstuvwxyzABCDEFGHI"))
print(string.reverse("abcdefghijklmnopqrstuvwxyzABCDEFGHIJ"))
print(string.reverse("abcdefghijklmnopqrstuvwxyzABCDEFGHIJK"))
print(string.reverse("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKL"))

print(string.reverse(1))
print(string.reverse(12))
print(string.reverse(123))
print(string.reverse(1234))
print(string.reverse(12345))
print(string.reverse(123456))
print(string.reverse(1234567))
print(string.reverse(12345678))
print(string.reverse(123456789))
print(string.reverse(1234567890))
print(string.reverse(12345678901))
print(string.reverse(123456789012))
print(string.reverse(1234567890123))
print(string.reverse(12345678901234))
print(string.reverse(123456789012343))

print(string.reverse(1.2))
print(string.reverse(1.02))
print(string.reverse(1.092))
print(string.reverse(1.0982))
print(string.reverse(1.09872))
print(string.reverse(1.098762))
print(string.reverse(1.0987652))
print(string.reverse(1.09876542))
print(string.reverse(1.098765432))
print(string.reverse(1.09876543212))
print(string.reverse(1.098765432123))
print(string.reverse(1.0987654321234))
print(string.reverse(1.09876543212345))

s = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKL"
for i = 1,10 do
	s = s .. s
end
print(string.reverse(s))

print((pcall((function() string.reverse() end))))
print((pcall((function() string.reverse(nil) end))))
print((pcall((function() string.reverse({}) end))))

